### ISSUE TITLE
podman: misplaced arguments cause go panic

### ISSUE THREAD

**Issue by dustymabe** [projectatomic/libpod#785] opened 2018-05-16 20:38 UTC
/kind bug

**Description**

misplaced arguments cause go panic. For example:
```
podman run -it registry.fedoraproject.org/fedora:28 --name weechat /bin/bash
```
 where 
```
sudo podman run -it --name weechat registry.fedoraproject.org/fedora:28  /bin/bash
```
 does not. Here is example of panic:

```
[dustymabe@dhcp137-98 ~]$ sudo podman run -it registry.fedoraproject.org/fedora:28 --name weechat /bin/bash 
panic: send on closed channel
        panic: close of closed channel

goroutine 11 [running]:
main.resizeTty.func1()
        /builddir/build/BUILD/libpod-d0fbfdc0accf4e491fdca778f6719e9158794108/_build/src/github.com/projectatomic/libpod/cmd/podman/utils.go:145 +0xe9
main.resizeTty.func2(0xc42031ecc0, 0xc4205e4360, 0xc420524c00)
        /builddir/build/BUILD/libpod-d0fbfdc0accf4e491fdca778f6719e9158794108/_build/src/github.com/projectatomic/libpod/cmd/podman/utils.go:154 +0x51
created by main.resizeTty
        /builddir/build/BUILD/libpod-d0fbfdc0accf4e491fdca778f6719e9158794108/_build/src/github.com/projectatomic/libpod/cmd/podman/utils.go:150 +0xeb
```

**Output of `podman version`:**

```
[dustymabe@dhcp137-98 ~]$ rpm -q podman
podman-0.5.1-1.gitd0fbfdc.fc28.x86_64
```

**Comment by mheon** [comment] 2018-05-16 22:41
It looks like this is an ordinary exit (no such command in the container, runc fails to start) that turned bad when attach errored. I'll check it out.

**Comment by mheon** [comment] 2018-05-16 22:49
This one is properly confusing. We're panicking because of an attempt to send to the resize channel in https://github.com/projectatomic/libpod/blob/master/cmd/podman/utils.go#L152-L154 when the channel is closed. The problem is the channel is only closed in one place, and it should only ever be closed once the function that sends has already returned. Therefore, there should never be a send on that channel when it is closed. I'll poke more tomorrow, but this is properly strange.

**Comment by giuseppe** [comment] 2018-05-17 09:00
there is a race condition as we close the channel both from the sender and the receiver side.  Since writing to a closed channel causes a panic, let's drop the close from the receiver side, I've opened a PR here: https://github.com/projectatomic/libpod/pull/787

**Closed** 2018-05-17 13:26 UTC
Labels: bug
