### ISSUE TITLE
podman commit: does not create entrypoint?

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#586] opened 2018-04-03 15:12 UTC
```
# podman run --name foo fedora date
Tue Apr  3 15:05:07 UTC 2018
# podman commit --quiet foo myimg
# podman run myimg
No command specified on command line or as CMD or ENTRYPOINT in this image
```
Expected: date output.

podman-0.3.5-1.gitdb6bf9e.fc27.x86_64

**Comment by mheon** [comment] 2018-04-03 15:15
Podman commit needs to be changed to accept an image config (entrypoint, CMD, etc). We can store the ones the container was created with on the podman side (they're probably in create config anyways) and feed them into commit.

**Comment by mheon** [comment] 2018-04-03 15:16
This should probably happen as part of the commit overhaul to use Buildah code and actually commit diffs (instead of export-import) that is covered by #520

**Comment by edsantiago** [comment] 2018-04-23 21:03
When and where should I expect to see this fixed? I'm still seeing the same behavior. Setup: 
```
podman-0.4.4.1524346805-gitcf1d884.fc27.x86_64
buildah-0.16-1524410543.gitd84f05a.fc27.x86_64
```
Curiously, if you `s/fedora/rhel7/` in comment 0, podman silently does nothing and exits 0. (No error message).

**Comment by mheon** [comment] 2018-04-23 21:11
The code has landed, so if it's not working, we have a new bug with the way we use buildah to commit.

**Comment by edsantiago** [comment] 2018-04-23 21:50
@TomSweeneyRedHat @baude can one of you perform the comment-0 test on what you believe should be a working system setup, and either reopen this issue or let me know what I've done wrong in my setup? TIA.

**Comment by rhatdan** [comment] 2018-04-24 11:56
Reopening issue to get confirmation of it working or not.

**Comment by mheon** [comment] 2018-04-24 14:37
@TomSweeneyRedHat Alright, so it's how we're calling into buildah to do a commit, then.

**Comment by mheon** [comment] 2018-04-24 14:38
@baude PTAL

**Closed** 2018-04-27 21:16 UTC
Labels: bug

**Comment by edsantiago** [comment] 2018-05-23 12:49
Has anyone tried the three steps in my first comment? Can you get them to work? What am I doing wrong?
```
# podman run --name foo fedora date
Wed May 23 12:46:26 UTC 2018
# podman commit --quiet foo myimg
8183e7f0a0185b1f307bfa7e01e8623f48f7d319de0ac3d55e2702136b16d7bc
# podman run myimg
No command specified on command line or as CMD or ENTRYPOINT in this image
```
buildah-1.00-1526305410.gitce8d467.fc27.x86_64
podman-0.5.4-1527007540.git926d07d.fc27.x86_64

**Comment by rhatdan** [comment] 2018-05-23 12:52
Do those commands work with Docker.
I think the issue is that you have not specified a CMD or Entrypoint, 
```
# podman commit --change "CMD=date" --quiet foo myimg
```

Should do what you want.  But if Docker automatically takes the CMD used to create the container then we have a bug.

**Comment by edsantiago** [comment] 2018-05-23 12:56
Oops - my bad, for not filing it as a docker-compat issue. Yes, docker uses the container's command as an entrypoint:
```
# docker run --name foo fedora date
Wed May 23 12:53:47 UTC 2018
# docker commit foo myimg
sha256:fd1fb7b03cd06c769b1eee0f14b659ed9fd5142c067a733e1e70658854ab7fe2
# docker run myimg
Wed May 23 12:54:08 UTC 2018
```

**Comment by rhatdan** [comment] 2018-05-23 12:56
Ok I just looked at this in Docker and the problem is podman does not populating the CMD field on the podman run command. I will open a PR>
