### ISSUE TITLE
podman prepends 'docker.io' to local image copied over from docker-daemon

### ISSUE THREAD

**Issue by miabbott** [projectatomic/libpod#639] opened 2018-04-18 19:57 UTC
/kind bug

Using `podman-0.3.5-2.gitdb6bf9e.fc28.x86_64` on Fedora 28 Atomic Workstation, I ran into the issue where `docker.io` was prepended to the name of a local image I had copied from the docker daemon.

```
$ sudo /usr/bin/docker images | grep myprecious
miabbott/myprecious                                latest              90bac9e2114b        6 weeks ago         1.06 GB

$ sudo podman pull docker-daemon:miabbott/myprecious:latest      
Getting image source signatures                                                    
Copying blob sha256:f9d6ec71b1b88be48969c2e2ba1e06599af912de7a3bae73503f64d01366d186
 251.74 MB / 251.74 MB [====================================================] 2s                                                                                                                                   
Copying blob sha256:4770739ee7b76e345f14d892da669622ef01bb6b73bf8ed557218454dfaab5ed   
 798.64 MB / 798.64 MB [====================================================] 6s                                                
Copying blob sha256:c4ee25c74390e508bcf684abe3221e6db4be313da1c6fca9bf345ca213725d84                                         
 375.00 KB / 375.00 KB [====================================================] 0s                                           
Copying config sha256:90bac9e2114b8daa29b1bf2ed56b6f292ff21bb993392ac2877a9a0fc4455900     
 3.55 KB / 3.55 KB [========================================================] 0s                                               
Writing manifest to image destination                                                                                  
Storing signatures                                                               
error pulling image "docker-daemon:miabbott/myprecious:latest": error retrieving local image after pulling docker-daemon:miabbott/myprecious:latest: invalid reference format

$ sudo podman images                                                
REPOSITORY                      TAG      IMAGE ID       CREATED       SIZE   
docker.io/library/busybox       latest   8ac48589692a   13 days ago   1.36MB     
docker.io/miabbott/myprecious   latest   90bac9e2114b   6 weeks ago   1.1GB
```

If you were to try to pull that `docker.io/miabbott/myprecious` image from the Docker Hub, it would fail because it only exists locally.

**Comment by mheon** [comment] 2018-04-18 20:17
@baude Is this the same issue we've seen before with c/image assuming a `docker.io` prefix on everything?

**Comment by baude** [comment] 2018-04-19 00:02
yes I think so ...

**Comment by whitel** [comment] 2018-04-23 21:42
I have the same experience when I build an image locally. Very simple example at https://github.com/whitel/testing-podman/

**Comment by mtrmac** [comment] 2018-04-24 14:33
AFAICS this is all podman.

- `Runtime.New` receives `name` as `docker-daemon:…`
- `Image.pullimage` parses the input using `alltransports.ParseImageName` and accepts it.
- `Runtime.getPullStruct` creates a `pullStruct{image: "docker-daemon:…"}`
- `Image.pullImage` returns the `.image` member, still `docker-daemon:…`
- `Runtime.New` assigns the value to `newImage.InputName`
- `Image.getLocalImage` passes it to `Runtime.getImage`
- … and `runtime.getImage` calls `Transport.ParseStoreReference(_, "docker-daemon:…")`, which is not a valid format for a c/storage reference.

I guess the intent was to ultimately `ParseStoreReference` with the value of `pullStruct.dstRef`.

(And again, _please_ stop using untyped strings, or at least, for each one, clearly define whether they should contain a `transport:reference`, `docker-like-reference`, or some other kind of string value.)

**Comment by mtrmac** [comment] 2018-04-24 14:35
(
Prepending of `docker.io/` to the pulled reference is ultimately due to the normalization happening in c/image, but

1. That’s not the immediate cause of the failure
2. podman does have the option to define a different name to use in the storage, probably by adding a `docker/daemon.Transport.Name` case in `getPullListFromRef` .

)

**Comment by rhatdan** [comment] 2018-04-24 15:08
@baude ^^

**Comment by baude** [comment] 2018-04-24 15:46
it cannot be podman when we exec buildah bud. its everywhere.

**Comment by rhatdan** [comment] 2018-05-25 09:52
This is fixed in the latest code.  We now product localhost/IMAGE

**Closed by rhatdan** 2018-05-25 09:52 UTC
Labels: bug

**Comment by yogeshgadge** [comment] 2023-06-15 21:34
This is happening with podman 4.5 in 2023

**Comment by rhatdan** [comment] 2023-06-15 22:42
Please open a new issue with the exact reproducer.
