### ISSUE TITLE
arg parsing: single-dash options expanded incorrectly

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#714] opened 2018-05-02 21:23 UTC
Sorry for the unhelpful title; I can't think of a better description. This one has been haunting me today:
```
# podman run centos find / -name sdf
find: unknown predicate `-n'
# podman run centos echo find / -name sdf
find / -n -a -m -e sdf
```
Somewhere in podman-land, `-name` is being rewritten and passed along as `-n -a -m -e`. 

podman-0.4.4-2.git9924956.fc27 and 0.5.1-1525212894.git970eaf0.fc27

**Comment by mheon** [comment] 2018-05-02 21:25
@baude This sounds like shortopts handling in urfave/cli

**Comment by rhatdan** [comment] 2018-05-02 21:26
Does it work if you do 

 podman run centos -- find / -name sdf

**Comment by rhatdan** [comment] 2018-05-02 21:28
Although the error looks like it is coming from the find command.

**Comment by edsantiago** [comment] 2018-05-02 21:33
```
#  podman run centos -- find / -name sdf
container create failed: container_linux.go:348: starting container process caused "exec: \"--\": executable file not found in $PATH"
: internal libpod error
```
also tried:
```
# podman run -- centos echo find / -name sdf
find / -n -a -m -e sdf
```
(Translation: AFAICT `--` is not telling podman to stop fiddling with args).

> Although the error looks like it is coming from the find command

Yes, because `find / -n` is not valid. `find` is one of those very weird old-style pre-posix commands that uses a single dash with long-name options.

**Comment by mheon** [comment] 2018-05-02 21:34
I know we had issues with shortopts handling early on (`podman run -ti ...` wouldn't work, you needed to explicitly specify `podman run -t -i ...`) that we fixed in `urfave/cli`. I suspect that fix has come back and bit us.

**Comment by TomSweeneyRedHat** [comment] 2018-05-02 21:35
@mheon yep, this smells very much like urfave cli.  I tried a number of twists without luck.  I'd thought off the bat that the '--' would work like Ed mentions, but it's not appearing to.

**Comment by rhatdan** [comment] 2018-05-02 21:42
podman run -- centos sh -c "find / -name sdf"
Works/

**Comment by rhatdan** [comment] 2018-05-02 21:44
But this is definately caused by our patch to urvave after seeing the echo example.  @baude You were involved in this patch, do you want to take a look.  I think we need to stop processing after the argv0

**Comment by edsantiago** [comment] 2018-06-20 12:21
Ping, I'm still seeing this, podman-0.6.3-1.gitcd39b62.fc28

**Comment by rhatdan** [comment] 2018-06-20 13:16
Yup noone has worked with upstream on this issue.

**Comment by vrothberg** [comment] 2018-06-28 13:51
I'll have a look. This bug is pretty annoying.

**Comment by rhatdan** [comment] 2018-06-28 14:30
@vrothberg That looks great to me.  Nice work.

**Comment by vrothberg** [comment] 2018-06-28 14:45
Damn, that's only a half fix as `podman run alpine ls -it` would be turned into `podman run alpine ls -i -t`.

**Comment by TomSweeneyRedHat** [comment] 2018-06-28 18:07
Yeah, I've tried dealing with urfave parsing in the past and you can get stuck in spidey webs real quick.

**Comment by edsantiago** [comment] 2018-06-28 18:28
Indeed. I've just surfaced from a couple of hours of ratholing in there. Useful as a golang learning exercise, but I got nowhere -- only far enough to suspect that the problem isn't fixable with this set of tools.

**Comment by vrothberg** [comment] 2018-06-28 20:05
I have a working solution by catching errors, but it's spaghetti goto. I'll draft a PR tomorrow and see what upstream thinks about it. The only other solution I see would be using another `flag` package.

**Comment by vrothberg** [comment] 2018-06-29 08:29
Here's a PR for urfave/cli (hopefully) fixing the issue: https://github.com/urfave/cli/pull/758

Smoke tests were successful and I think there are no side effects.

**Comment by rhatdan** [comment] 2018-06-29 09:39
@vrothberg Won't this still fail if you do an command like

podman run fedora find / -printf ...

Will urvave still see this as a valid -i and -t?

Would a better fix to be just stop interpreting the options after the `fedora` object when we tell it don't sort the options.

**Comment by vrothberg** [comment] 2018-06-29 09:44
> Would a better fix to be just stop interpreting the options after the fedora object when we tell it don't sort the options.

That's what's happening actually. `set.Parse(args)` will stop interpreting input as flags/options when hitting `fedora`. Everything after that will be interpreted as arguments.

**Comment by vrothberg** [comment] 2018-06-29 09:46
>podman run fedora find / -printf ...
>
> Will urvave still see this as a valid -i and -t?

No it won't. It will stop at `fedora` and use the remainder as arguments.

**Comment by rhatdan** [comment] 2018-06-29 10:06
Awesome.

**Comment by vrothberg** [comment] 2018-06-29 10:07
@rhatdan To be more specific. The parsing errors the patch is catching are always on the left side of the specified image. For instance, when running `podman run -it fedora:latest ls -it`:

- we'll catch the error that `-it` is not defined and transform that into `-i -t`
- then we reparse everything again with `podman run -i -t fedora:latest ls -it`

What the patch also does is to make sure that all short flags in `-abc` are actually defined in the FlagSet, so we get a `-abc is not defined` instead of a `-c is not defined`.

**Comment by rhatdan** [comment] 2018-06-29 10:17
My fear looking through the PRs, there has not been anything merged since Feb 21st.  I am not sure how alive this project is.

We might need to carry this patch some how.

**Comment by vrothberg** [comment] 2018-07-04 06:48
> We might need to carry this patch some how.

I begin to share your fear. Given the bug is blocking some common usage patterns, I'd like to push it a bit forward and carry the patch until `urfave/cli` is revived. Any objections against committing the change on `vendor/github.com/urfave/cli`?

**Comment by rhatdan** [comment] 2018-07-04 11:59
If you modify the vendor.conf to point at your repo from vendor/github.com/urfave/cli then I think we can carry it.

Something like 
github.com/urfave/cli UUID https://github.com/vrothberg/cli

**Comment by vrothberg** [comment] 2018-07-04 12:18
Done. I opened a PR: https://github.com/projectatomic/libpod/pull/1046

**Closed** 2018-07-05 10:43 UTC
Labels: bug
