### ISSUE TITLE
Bug: Cannot resolve DNS from inside the container

### ISSUE THREAD

**Issue by Drakonis** [projectatomic/libpod#390] opened 2018-02-22 22:50 UTC
Currently containers are incapable of resolving DNS, including --net=host when creating the container enables DNS resolving.

**Comment by baude** [comment] 2018-02-22 23:21
can you try something like:

```
iptables -t filter -I FORWARD -i cni0 ! -o cni0 -j ACCEPT
```

and see if that fixes things?

**Comment by Drakonis** [comment] 2018-02-22 23:28
yeah it is working now.

**Comment by mheon** [comment] 2018-02-22 23:34
Sounds like iptables-allow in CNI would fix this (https://github.com/containernetworking/plugins/pull/75). Hopefully we can speed that along.

**Comment by vrothberg** [comment] 2018-03-01 13:36
Is it possible to add a (temporary) workaround to `podman` until the issue is resolved in CNI?

**Comment by mheon** [comment] 2018-03-01 14:37
The original plan was to wait until the CNI PR merged, but that's been stalled upstream for a long time now. Given that, I think we need to include a local fix until it merges.

**Comment by rhatdan** [comment] 2018-03-01 18:29
@baude Can you add a temporary hack, and we can remove once new version of CNI happens.

**Comment by baude** [comment] 2018-03-02 20:34
yup! its in now

**Closed by baude** 2018-03-02 20:34 UTC

**Comment by vrothberg** [comment] 2018-03-03 13:54
I just tested it in openSUSE and it works like a charm. Thanks a lot, @baude!

**Comment by rhatdan** [comment] 2018-03-04 16:01
Nice,  Any chance you could write a blog about podman on OpenSuse?

**Comment by vrothberg** [comment] 2018-03-05 09:03
> Nice, Any chance you could write a blog about podman on OpenSuse?

@rhatdan Sure, with pleasure. I can send you a draft via email if you want to have a look. I should find some time this week to write it.

**Comment by rhatdan** [comment] 2018-03-07 05:48
Looking forward to it.
