### ISSUE TITLE
podman with bind mount leaving cgroup debris and prevents container restart

### ISSUE THREAD

**Issue by aalba6675** [projectatomic/libpod#730] opened 2018-05-06 02:30 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
>
> /kind feature

**Description**

When podman stops a systemd container with bind mounts, it leaves behind a lot of cgroup debris.
This prevents the container from starting the **third** time.

**Steps to reproduce the issue:**

1. Workaround: currently to get working bind mounts I have to set `mount --make-private /tmp`. Otherwise oci-systemd-hook cannot move the mount to the overlay. This on Fedora 28. https://github.com/projectatomic/oci-systemd-hook/issues/92

2. Create a systemd-based fedora:28 container
```
podman create --name bobby_silver -v /srv/docker/volumes/podman/home:/home:z   --env container=podman  --entrypoint=/sbin/init --stop-signal=RTMIN+3 fedora:28
```

3. Start container 3 times
```
podman start bobby_silver
podman stop bobby_silver
podman start bobby_silver
podman stop bobby_silver
podman start bobby_silver
podman stop bobby_silver
```

**Describe the results you received:**
After first start/stop cycle there is cgroup debris:
```
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0 type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

```
## third time unlucky
unable to start container "bobby_silver": container create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/containers/storage/overlay/52f7959a1a8a171b2c8aee587ea81c964e84130681444f0ff03b3202804a91cb/merged\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0: no such file or directory\\\"\""
```

journal
```
May 06 10:37:05 podman.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
May 06 10:37:05 podman.localdomain audit: ANOM_PROMISCUOUS dev=vethd814e8bb prom=256 old_prom=0 auid=1050 uid=0 gid=0 ses=3
May 06 10:37:05 podman.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): vethd814e8bb: link is not ready
May 06 10:37:05 podman.localdomain kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethd814e8bb: link becomes ready
May 06 10:37:05 podman.localdomain kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
May 06 10:37:05 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered blocking state
May 06 10:37:05 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered disabled state
May 06 10:37:05 podman.localdomain kernel: device vethd814e8bb entered promiscuous mode
May 06 10:37:05 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered blocking state
May 06 10:37:05 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered forwarding state
May 06 10:37:05 podman.localdomain NetworkManager[1159]: <info>  [1525574225.9736] device (vethd814e8bb): carrier: link connected
May 06 10:37:05 podman.localdomain NetworkManager[1159]: <info>  [1525574225.9747] manager: (vethd814e8bb): new Veth device (/org/freedesktop/NetworkManager/Devices/12)
May 06 10:37:05 podman.localdomain systemd-udevd[18311]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
May 06 10:37:05 podman.localdomain systemd-udevd[18311]: Could not generate persistent MAC address for vethd814e8bb: No such file or directory
May 06 10:37:05 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=89
May 06 10:37:05 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=91
May 06 10:37:05 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=92
May 06 10:37:05 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=93
May 06 10:37:05 podman.localdomain audit: NETFILTER_CFG table=filter family=2 entries=155
May 06 10:37:06 podman.localdomain conmon[18363]: conmon cd8be22a52efaed7e279 <ninfo>: about to waitpid: 18364
May 06 10:37:06 podman.localdomain kernel: SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
May 06 10:37:06 podman.localdomain oci-systemd-hook[18389]: systemdhook <error>: cd8be22a52ef: pid not found in state: Success
May 06 10:37:06 podman.localdomain conmon[18363]: conmon cd8be22a52efaed7e279 <error>: Failed to create container: exit status 1
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=filter family=2 entries=156
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=94
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=96
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=94
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=96
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=10 entries=78
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=10 entries=80
May 06 10:37:06 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered disabled state
May 06 10:37:06 podman.localdomain audit: ANOM_PROMISCUOUS dev=vethd814e8bb prom=0 old_prom=256 auid=1050 uid=0 gid=0 ses=3
May 06 10:37:06 podman.localdomain kernel: device vethd814e8bb left promiscuous mode
May 06 10:37:06 podman.localdomain kernel: cni0: port 2(vethd814e8bb) entered disabled state
May 06 10:37:06 podman.localdomain NetworkManager[1159]: <info>  [1525574226.1560] device (vethd814e8bb): released from master device cni0
May 06 10:37:06 podman.localdomain gnome-shell[3393]: Removing a network device that was not added
May 06 10:37:06 podman.localdomain gnome-shell[2067]: Removing a network device that was not added
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=94
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=93
May 06 10:37:06 podman.localdomain audit: NETFILTER_CFG table=nat family=2 entries=91
```

**Describe the results you expected:**
start/stop without any issue

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:       0.5.2-dev
Go Version:    go1.10.1
OS/Arch:       linux/amd64


```

**Output of `podman info`:**

``
host:
  MemFree: 17688948736
  MemTotal: 33667493888
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  hostname: podman.localdomain
  kernel: 4.16.5-300.fc28.x86_64
  os: linux
  uptime: 10h 3m 7.91s (Approximately 0.42 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
store:
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
  - overlay.override_kernel_check=true
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* physical
* Fedora 28

**Comment by aalba6675** [comment] 2018-05-06 02:31
After getting into this situation, I can't start non-bind mounted containers.
alice_gold is a Fedora:28 container without any bind mounts
```
unable to start container "alice_gold": container create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"cgroup\\\" to rootfs \\\"/var/lib/containers/storage/overlay/bc6d5e48c36118d012e5996158e5f7de7c0bd386b63cda3be40686a90203c019/merged\\\" at \\\"/sys/fs/cgroup\\\" caused \\\"stat /sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-conmon-2a5aee03fd0d0c99666543c00c5943a507aee7a6c6cbf932a714e3d090a85ea5/2a5aee03fd0d0c99666543c00c5943a507aee7a6c6cbf932a714e3d090a85ea5: no such file or directory\\\"\""
: internal libpod error
```

**Comment by aalba6675** [comment] 2018-05-06 02:32
If I don't use bind mounts at all and leave `/tmp` as `mount --make-shared`, then all non-bind mount containers work: they can be start/stop without any cgroup debris.

**Comment by rhatdan** [comment] 2018-05-06 12:18
@mrunalp I think this might be runc not running posthook oci-systemd-hook.

@aalba6675 Could you see if the journal reports that oci-systemd-hook ran in the posthook?

**Comment by aalba6675** [comment] 2018-05-06 13:03
@rhatdan  The posthook doesn't seem to be run. This is the journal when the container is stopped. Leaving behind a lot of cgroup mounted on impossibly long paths like
```
/sys/fs/cgroup/systemd/libpod_parent/libpod-conmon-
cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/
libpod_parent/libpod-conmon-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0
/cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/libpod_parent/libpod-
conmon-
cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/cd8be22a52efaed7e2790d
2eb3421c00542c3eb9763bfe715c3ad23647c419e0 type cgroup 
(rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)```
```
May 06 20:58:29 podman.localdomain audit[5949]: SERVICE_STOP pid=5949 uid=0 auid=1050 ses=3 subj=system_u:system_r:container_t:s0:c124,c228 msg='unit=dbus comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 06 20:58:29 podman.localdomain audit[5949]: SERVICE_STOP pid=5949 uid=0 auid=1050 ses=3 subj=system_u:system_r:container_t:s0:c124,c228 msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 06 20:58:29 podman.localdomain audit[6133]: SYSTEM_SHUTDOWN pid=6133 uid=0 auid=1050 ses=3 subj=system_u:system_r:container_t:s0:c124,c228 msg=' comm="systemd-update-utmp" exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
May 06 20:58:29 podman.localdomain audit[5949]: SERVICE_STOP pid=5949 uid=0 auid=1050 ses=3 subj=system_u:system_r:container_t:s0:c124,c228 msg='unit=systemd-update-utmp comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 06 20:58:29 podman.localdomain audit[5949]: SERVICE_STOP pid=5949 uid=0 auid=1050 ses=3 subj=system_u:system_r:container_t:s0:c124,c228 msg='unit=systemd-tmpfiles-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
May 06 20:58:29 podman.localdomain conmon[5938]: conmon cd8be22a52efaed7e279 <ninfo>: container 5949 exited with status 0
```

**Comment by aalba6675** [comment] 2018-05-06 13:05
Is there a way to manually clear these cgroups/mounts? Once I get into this state I can't start simple containers (i.e. those without bind mounts).

**Comment by rhatdan** [comment] 2018-05-06 13:10
Can't you just umount them?

**Comment by aalba6675** [comment] 2018-05-06 13:28
Another observation: notify_on_release is 0 in the `/sys/fs/cgroup/systemd/libpod_parent` hierarchy.

**Comment by mheon** [comment] 2018-05-06 20:12
CGroups issue could be related to #496 
#507 may fix it, but has serious issues with Systemd-managed CGroups that still need to be solved.

**Comment by aalba6675** [comment] 2018-05-07 00:34
@mheon  - any idea why this would be triggered by a kludgy bind mount (`mount --make-private /tmp`)?

Non-bind mount containers are functioning without leaving group debris .

Once this situation is triggered (lots of cgroup mounted on `/sys/fs/cgroup/systemd/libpod_parent/<long non existent path with uuid repeated>`), then even non-bind mount containers could no longer be started.

**Comment by mheon** [comment] 2018-05-07 00:47
@aalba6675 The mounts situation makes it sound like it could be oci-umount-hook firing, and less like our other CGroup issues (though it's wierd you're not seeing CGroups left over even in cases where mounts aren't involved, we should still be leaking one or two). I'm not familiar enough with that hook to know for sure what the cause might be, though.

**Comment by aalba6675** [comment] 2018-05-07 01:47
@mheon you are right, I spoke too soon. The cgroups are only visible in the legacy tools libcgroup-tools.

```
lscgroup | grep libpod_parent
cpu,cpuacct:/libpod_parent
cpu,cpuacct:/libpod_parent/libpod-conmon-9a3f523c5c1055be951b2635c9371372f0de0ead65129da8bbab9c21a63f82e6
cpu,cpuacct:/libpod_parent/libpod-conmon-85b047f7598912928dd50ae435e932d8f6d36340bd29d94378cd76c04c1b9d3a
cpu,cpuacct:/libpod_parent/libpod-conmon-85b047f7598912928dd50ae435e932d8f6d36340bd29d94378cd76c04c1b9d3a/85b047f7598912928dd50ae435e932d8f6d36340bd29d94378cd76c04c1b9d3a
cpu,cpuacct:/libpod_parent/libpod-conmon-f31ddb42076b6f92fa4e3528aa69e3835657bac718a15fa1f21eded28d33df6d
cpu,cpuacct:/libpod_parent/libpod-conmon-9616fc8f2a42ad9276f4b65bf20aa48f1d921a3b56433b7b0c17799c7d48f5df
cpu,cpuacct:/libpod_parent/libpod-conmon-9616fc8f2a42ad9276f4b65bf20aa48f1d921a3b56433b7b0c17799c7d48f5df/9616fc8f2a42ad9276f4b65bf20aa48f1d921a3b56433b7b0c17799c7d48f5df
devices:/libpod_parent
devices:/libpod_parent/libpod-conmon-9a3f523c5c1055be951b2635c9371372f0de0ead65129da8bbab9c21a63f82e6
devices:/libpod_parent/libpod-conmon-85b047f7598912928dd50ae435e932d8f6d36340bd29d94378cd76c04c1b9d3a
```

The are however not mount in the form of `/sys/fs/cgroup/systemd/libpod_parent/....` as in the bind mount case.

**Comment by mheon** [comment] 2018-05-07 02:07
The recursive CGroup path seems like a separate bug - our current CGroup issues are mainly a lack of cleanup, whereas this seems to actually be duplicating the Conmon scope repeatedly. Interesting - I'll look at this more tomorrow.

**Comment by aalba6675** [comment] 2018-05-07 02:27
Thanks! Let me summarize a reproducer for Fedora 28:
```
## prolog
mount --make-private /tmp
mkdir -p /volumes/podman/home
semanage fcontext -a -e /var/lib/containers /volumes
restorecon -R /volumes

podman create --name bobby_silver --env container=podman --entrypoint /sbin/init --stop-signal=RTMIN+3  \
    -v /volumes/podman/home:/home:z fedora:28

## now start stop 3 times
podman start bobby_silver; podman stop bobby_silver
podman start bobby_silver; podman stop bobby_silver
podman start bobby_silver; podman stop bobby_silver
# the third time will fail; there will be lots of mount type cgroup leakage, i.e., the cgroup will be mounted on paths like
# /sys/fs/cgroup/systemd/libpod_parent/(libpod-conmon-<uuid>/<uuid>)*
# these leaks cannot be unmounted or cleaned up
# trying to start a different stateless container should fail now
```

**Comment by mheon** [comment] 2018-05-08 18:04
To provide an update here, I'm working on a more general overhaul of our CGroup handling now. Hopefully, once it's ready, it will address this and our other CGroup issues.

**Comment by mheon** [comment] 2018-05-09 18:56
My original thought was that this was the oci-umount hook, given that it seems to only occur with mounts. However, oci-umount does nothing with CGroups, so that doesn't seem likely. oci-systemd-hook does use both mounts and CGroups, so that seems to be a likely candidate.

**Comment by rhatdan** [comment] 2018-05-10 15:17
Yes this is definately oci-systemd-hook, but the problem, I believe, is runc is not firing the oci-systemd-hook in poststop.

**Comment by wking** [comment] 2018-05-11 20:17
In some discussion on `#podman` with @baude and @mhean, the solution to this may be defining a `postexit` extension stage (groundwork in #758).  We wouldn't set those hooks in the OCI config, because the OCI spec [contains no post-exit hooks][1] (see also discussion about adding new hooks to the spec in opencontainers/runtime-spec#926), but we could pass them through to `conmon` via the `--exit-command` it grew in kubernetes-incubator/cri-o#1366 (and which we don't actually use yet despite the option having been added [to support podman use cases][2]).

[1]: https://github.com/opencontainers/runtime-spec/blob/v1.0.1/config.md#posix-platform-hooks
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1366#issuecomment-368052671

**Comment by aalba6675** [comment] 2018-05-14 13:30
Hi I have an observation not related to exit/posthook: when the container is merely **started** there is already a doubled path. 

Container is running (not tried to exit at all):

```cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
cgroup on /sys/fs/cgroup/systemd/libpod_parent/libpod-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/ctr/libpod_parent/libpod-cd8be22a52efaed7e2790d2eb3421c00542c3eb9763bfe715c3ad23647c419e0/ctr type cgroup (rw,nosuid,nodev,noexec,relatime,seclabel,xattr,name=systemd)
```

**Comment by mheon** [comment] 2018-05-14 13:32
@aalba6675 Is this after a restart (container has already started and stopped once, then started again)?

**Comment by aalba6675** [comment] 2018-05-14 13:33
@mheon - no - this is a clean start from boot with the `mount --make-private /tmp` just to get the bind mounts working.

**Comment by aalba6675** [comment] 2018-05-14 13:34
It seems that if I take the trouble to `umount <double_path>; umount <single_path>;` from the host, the container can be start/stop without any issues.

**Comment by mheon** [comment] 2018-05-14 13:36
@aalba6675 I think we may have separate yet related issues, then. We aren't cleaning up CGroup paths because the OCI poststop hook isn't firing, and somewhere inside `oci-systemd-hook` we are duplicating CGroup paths. The more severe one is the poststop hooks not firing, as it seems that if cleanup is done, we can still use the container. Still, doubling CGroup paths is really not a good thing.

**Comment by aalba6675** [comment] 2018-05-14 13:38
Looks weird the doubled path - I can confirm that manually cleaning up the mounts from the host (single/double) paths allows the container to be start/stop indefinitely. This explains a bit to why I was seeing triple/quad paths. When starting the container without cleanup a second time the start hook must have add the triple/quad paths ad infinitum...until some limit was reached.

**Comment by rhatdan** [comment] 2018-05-14 20:41
The oci-systemd-hook code firsts mounts a tmpfs on /sys/fs/cgroup, then it goes through and creates mountpoints on that directory.  In the last step it remounts the directory on itself read-only, which is causing the "double mounts.

```

	/* Mount tmpfs at new cgroup directory */
	if (mount("tmpfs", cgroup_path, "tmpfs", MS_NODEV|MS_NOSUID, options) == -1) {
		pr_perror("%s: Failed to mount tmpfs at %s", id, cgroup_path);
		return -1;
	}
	if ((makepath(systemd_path, 0755) == -1) && (errno != EEXIST)) {
		pr_perror("%s: Failed to mkdir new dest: %s", id, systemd_path);
		return -1;
	}
	if (remount_readonly(id, cgroup_path, cgroup_path) < 0) {
		return -1;
	}
```

**Comment by mheon** [comment] 2018-05-14 20:44
Alright, so we are expecting a doubled mount - the issue is only poststop hooks not firing.

**Comment by aalba6675** [comment] 2018-05-16 01:07
@rhatdan would you know what logic will cause path doubling: `/sys/fs/cgroup/systemd/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr/libpod_parent/libpod-6cab0d8c9dc817e69fd0c02a7657e9a83edab3903f25f50d758c1511283bbbf0/ctr`. 

Is this intended? I guess there must be some `find cgroup path and append` path  logic happening. Also this only happens in when use `--volumes`.

**Comment by rhatdan** [comment] 2018-05-16 13:17
Does it happen with any --volumes?  It could be a leaked mount point.

**Comment by aalba6675** [comment] 2018-05-29 05:02
Splitting off into a separate issue as the startup of container may be different from cleanup.

**Comment by mheon** [comment] 2018-05-29 20:57
So I'm looking at this again, and I think we might have an actual podman/runc interaction bug with `oci-systemd-hook` - the postrun hook should be triggering when we call `runc delete` and we definitely are calling that as part of restarting a container (https://github.com/projectatomic/libpod/blob/master/libpod/container_internal.go#L552 calls https://github.com/projectatomic/libpod/blob/master/libpod/oci.go#L567). So the conditions for the postrun hook triggering are being fulfilled, but the hook itself is not firing - worth looking into.

**Comment by mheon** [comment] 2018-05-29 21:59
I threw on some debug statements, and the hooks are definitely being added to the spec.
@wking Given that we are adding the hooks to the spec, and `runc delete` is being called, do you think this sounds like a `runc` bug?

**Comment by wking** [comment] 2018-05-29 22:20
On Tue, May 29, 2018 at 02:59:24PM -0700, Matthew Heon wrote:
> @wking Given that we are adding the hooks to the spec, and `runc
> delete` is being called, do you think this sounds like a `runc` bug?

Sounds like it to me.  But given runc's current lack of hook tests and
glacial pace at addressing known hook issues
(opencontainers/runc#1057, opencontainers/runc#1696,
opencontainers/runc#1710, opencontainers/runc#1738,
opencontainers/runc#1741, opencontainers/runc#1797, and possibly
more), I don't know if I'd expect much after filing an issue or pull
request.

Is there anything blocking us moving forward on shifting hook
invocation into libpod itself?  If we wanted to fire the post-delete
hooks ourselves after deleting the runtime, we should have everything
we need to do that (and we avoid the issues around defining our own
new stage [1]).  If it sounds appealing, I can work up a libpod PR.

[1]: https://github.com/projectatomic/libpod/pull/758#discussion_r188377662

**Comment by mheon** [comment] 2018-05-30 15:51
I have no issue with doing this ourselves if we can't rely on the runtime to do it reliably. Would you call this an extension stage, or would we just be taking over the responsibility of running `poststop` hooks given that the runtime can't be relied upon to run them?

**Comment by wking** [comment] 2018-05-30 16:16
> Would you call this an extension stage, or would we just be taking over the responsibility of running poststop hooks given that the runtime can't be relied upon to run them?

I'll adjust the extension stage handling to allow callers to take over OCI stages when they want to.

**Comment by aalba6675** [comment] 2018-05-31 03:10
@mheon what is it about a host volume mount `-v /abcd:/abcd:z`  that makes this problem manifest itself? Without the host volume mount things appear to work :).

**Comment by mheon** [comment] 2018-05-31 13:14
That's a good question... Especially since we are already bind-mounting some things into every container (`/etc/resolv.conf`, for example - we make a copy of the host's resolv for every container and bind-mount it in). I don't know how those are different from user-specified mounts for this.

**Comment by mheon** [comment] 2018-06-14 20:37
@aalba6675 Can you try this with Podman 0.6.2 to see if it's fixed? We execute postrun hooks ourselves now, instead of calling out to `runc`, so cleanup of the mounts should be happening now.

**Comment by thoraxe** [comment] 2018-06-17 00:56
I was able to cause this problem with 0.6.2 but I'm not sure how to reproduce it or unmount the cgroups...

**Comment by mheon** [comment] 2018-06-18 18:07
Verified here. We're further than we were before - `oci-systemd-hook` is actually running. Now it's throwing errors. This may actually be an `oci-systemd-hook` bug.

**Comment by mheon** [comment] 2018-06-19 13:01
I spent some more time debugging this yesterday. New conclusions:

- `oci-systemd-hook` is being correctly called and is running, but incorrectly has a dependency on the `PID` part of state and will refuse to start if it is not set in the post-hook. This is nonsensical, as postdelete hooks run after the container has definitely stopped and does not have a PID. Fix for this will need to be in oci-systemd-hook
- However, `oci-systemd-hook` is not responsible for performing cleanup of the CGroup mounts we see leaking. The code assumes that they will be cleaned up when the container's mount namespace closes. This assumption does not seem to be holding true for cases where the container has volume mounts.

**Comment by rhatdan** [comment] 2018-06-19 13:18
Matt did you attempt to remove the pid failure, and it still failed to find the directory or was this just on a non systemd container

**Comment by mheon** [comment] 2018-06-19 13:22
@rhatdan I do believe we had another error, let me see what that was

**Comment by rhatdan** [comment] 2018-06-19 15:13
So in this case everything was cleaned up correct?

**Comment by mheon** [comment] 2018-06-19 15:19
It looks like everything is being cleaned up with no volume mounts present, but I'm not 100% sure, given that `oci-systemd-hook` is still throwing errors. With volume mounts, I can't get systemd to do anything except exit instantly, so I think I must be doing something wrong.

**Comment by mheon** [comment] 2018-06-19 15:21
I can confirm that, while the container is exiting instantly if mounts are present, it is leaving mounts lying around in `/tmp`.
`
tmpfs on /tmp/ocitmp.Rvr8xj type tmpfs (rw,nosuid,nodev,relatime,context="system_u:object_r:container_file_t:s0:c172,c562",size=65536k,mode=755)
tmpfs on /tmp/ocitmp.Rvr8xj/.containerenv type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /tmp/ocitmp.Rvr8xj/secrets type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
`

**Comment by aalba6675** [comment] 2018-06-20 00:56
@mheon I think you are seeing cascading effects of bugs:

The `/tmp` stuff is due to default `mount --make-shared`; the container startup bails leaking the `ocitmp` mount; Reported here https://github.com/projectatomic/oci-systemd-hook/issues/92

#893 - may also be a duplicate of this bug; it you don't clean up the cgroups mount manually on the host after your ExecReload, the cgroup will leak and you will see the "explosion".

**Comment by mheon** [comment] 2018-06-20 01:04
@aalba6675 I think #893 is probably separate, as the CGroups mounts aren't being created there - `oci-systemd-hook` will only run on containers with `init` set as command, which is not true for the containers there. Therefore, we shouldn't have any CGroup mounts present at all there. I think that might be a result of our CGroup handling conflicting with systemd's.

On `/tmp` - my development VM is still on F27, but `/tmp` is definitely shared propagation. So I think I am indeed hitting that bug.

**Comment by aalba6675** [comment] 2018-06-20 01:05
A workaround is to patch the template to `/tmp/oci/octmp.XXXX` and have `/tmp/oci` `--make-private`.

**Comment by rhatdan** [comment] 2018-06-20 12:14
First off we should probably not use /tmp at all, except for when we are doing this as a non privileged user.  We should be doing this under /run/libpod

**Comment by aalba6675** [comment] 2018-06-20 12:51
On Fedora 28 /run has shared propagation, so this would at least need a tmpfs at /run/libpod/tmp with private propagation then use a template like /run/libpod/tmp/ocitmp.XXXXXX.

**Comment by rhatdan** [comment] 2018-06-20 12:56
How about https://github.com/projectatomic/oci-systemd-hook/pull/98 to fix this?

**Comment by rhatdan** [comment] 2018-06-20 12:56
Could you try it out.

**Comment by rhatdan** [comment] 2018-07-12 18:33
@aalba6675 Could you checkout podman-0.7.1 which added podman container cleanup which could fix some of these issues.

**Closed** 2018-07-17 19:33 UTC
Labels: bug
