### ISSUE TITLE
Podman exits immediately when running as non-root user

### ISSUE THREAD

**Issue by aengelke** [projectatomic/libpod#1070] opened 2018-07-10 10:02 UTC
> /kind bug

**Description**

When running `podman` as non-root user, the program exits immediately with status code zero. This is presumably from [cmd/podman/main.go:35](https://github.com/projectatomic/libpod/blob/master/cmd/podman/main.go#L35), where exit is called when we *became* root in the user namespace. (Note that `became` is `false` if and only if an error occurred -- this is already cought above.) Also, exit code zero doesn't make sense to me.

**Steps to reproduce the issue:**

1. Run `podman` as non-root

**Describe the results you received:**

Nothing happens

**Describe the results you expected:**

Help output

**Output of `podman version`:**

```
Version:       0.6.5
Go Version:    go1.10.3
OS/Arch:       linux/amd64
```

(as included in Silverblue; version 28.20180707.0)

**Comment by mheon** [comment] 2018-07-10 14:32
Can reproduce locally here on latest master. Going to take a look today.
@giuseppe This looks like the rootless issues @umohnani8 had as well.

**Comment by mheon** [comment] 2018-07-10 14:40
I don't think this is actually that line in main, though - the parent will be killed, but the child should still be running in the user namespace created for Podman.

**Comment by giuseppe** [comment] 2018-07-10 14:42
@mheon I can assign it to myself if you are fine, I had a similar issue when using `-ti` with selinux enabled, just to be sure it is the same one I am seeing, could you try with `semodule -DB` and see if there is any AVC in the journal?

**Comment by mheon** [comment] 2018-07-10 15:03
@giuseppe Not SELinux - I'm seeing no denials even with dontaudit turned off

**Comment by aengelke** [comment] 2018-07-10 15:07
No AVC denials in the journal, independently of SELinux configuration.

**Comment by mheon** [comment] 2018-07-10 15:16
This only appears to happen with packaged Podman - can't reproduce on source builds. My earlier test with latest master was actually a 0.6.5 RPM - I was using the wrong binary. Oops.

**Closed** 2018-07-10 17:18 UTC

**Comment by aengelke** [comment] 2018-07-10 17:53
Thanks for the quick fix (and the workaround)!
