### ISSUE TITLE
podman attach: There Can Be Only One (tty)

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/libpod#580] opened 2018-04-02 19:40 UTC
Synopsis: podman run, then podman attach, the latter steals stdout (but not stdin) from the former:
```
w1# podman run --name foo --interactive fedora cat
hi from run     <-- type this
hi from run     <-- get this
```
Now, in a separate window:
```
w2# podman attach foo
hi from attach    <-- type this
hi from attach    <-- get this
```
Note that `w1` does not get `hi from attach`. Should it? With docker, output goes to both.

Now go back to `w1` and type `hi again from run`. It will not echo in `w1`, but will echo (in real time) in `w2`. Hit Enter, and the second copy (from `cat`) is also output in `w2` but not `w1`. `^D` in either window terminates the container.

podman-0.3.5-1.gitdb6bf9e.fc27.x86_64

**Comment by mheon** [comment] 2018-04-02 19:43
Given that all our terminal ops are happening over a unix socket, I don't think there is any inherent reason why we can't have multiple connections going at once.

As it sounds now, though, I think conmon is probably dumping the first connection after another is made

**Comment by mheon** [comment] 2018-04-02 19:49
Yeah, confirmed, `conmon` stores only one connection socket - https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L587

Once a new connection comes in, that FD is overwritten, and `conmon` stops copying to it.

We should theoretically be able to make that a list of FDs and copy to all of them instead of just one. I'll open an issue upstream.

**Comment by rhatdan** [comment] 2018-04-02 20:04
Makes sense to me.

**Comment by mheon** [comment] 2018-04-03 22:36
CRI-O https://github.com/kubernetes-incubator/cri-o/pull/1483 should fix

**Comment by mheon** [comment] 2018-04-09 19:35
CRI-O PR was merged. We should pix up the fix in the next release.

**Closed by mheon** 2018-04-09 19:35 UTC

**Comment by edsantiago** [comment] 2018-06-11 20:45
Fixed in podman-0.6.2-10.git72c0b4f.fc28.x86_64

**Comment by kushaldas** [comment] 2018-06-18 16:43
Using  podman-0.6.2-10.git72c0b4f.fc28.x86_64 in one vm, I am not getting the echo in that example command.

```
# podman run --name foo --interactive fedora:28 cat
Hello
^C^\^Z^Z
```
Only pressing `Ctrl+d` disconnects from the container.

**Comment by mheon** [comment] 2018-06-18 16:48
@kushaldas Multiple attaches (a `podman attach` after `podman run`) or just one?

**Comment by edsantiago** [comment] 2018-06-18 16:54
@kushaldas first of all, I would not expect ^C or ^Z to have any effect on an interactive cat. However: in your excerpt, are you typing `Hello` followed by enter, and then _not seeing a second Hello_? That's alarming. If this is the case, what is your `$TERM`?

**Comment by kushaldas** [comment] 2018-06-19 15:10
>@kushaldas Multiple attaches (a podman attach after podman run) or just one?
In both cases.

**Comment by kushaldas** [comment] 2018-06-19 15:11
>what is your `$TERM`?

```
$ echo $TERM
xterm-256color
```

**Comment by mheon** [comment] 2018-06-19 15:14
Hm. Sending EOF via `Ctrl-D` exits attach... If you run a `bash` container and type in `exit`, will it also exit? I want to see if input is being correctly forwarded into the container. Output is definitely not making it out.

**Comment by kushaldas** [comment] 2018-06-19 15:21
@mheon if I use `-it`, then nothing happens on the terminal, it just stays hanged there.

**Comment by mheon** [comment] 2018-06-19 15:23
Alright, so input is not being forwarded either, then

**Comment by kushaldas** [comment] 2018-06-19 15:24
>Hm. Sending EOF via Ctrl-D exits attach... If you run a bash container and type in exit, will it also exit? I want to see if input is being correctly forwarded into the container. Output is definitely not making it out.

It seems so, 

```
# podman run --name foo2 --interactive fedora:28 bash
exit
#
```

**Comment by mheon** [comment] 2018-06-20 19:22
Got a shell on the system where this reproduces. I think I've tracked down the cause - syslog is getting spammed with 
`conmon[5988]: conmon 7fb208f490dfd2229a50 <nwarn>: write_k8s_log failed`

Not sure why yet, checking the `conmon` code to see if anything jumps out

**Comment by mheon** [comment] 2018-06-20 19:31
The error seems to be in `conmon` in `set_k8s_timestamp()` - https://github.com/kubernetes-incubator/cri-o/blob/master/conmon/conmon.c#L284-L316

**Comment by mheon** [comment] 2018-06-20 20:05
I initially thought this was going to be an issue accessing the realtime clock or something similar, but we are actually producing timestamps too long for the conmon buffer

**Comment by mheon** [comment] 2018-06-20 20:06
For reference, the generated timestamp:
`2018-06-21T01:33:55.102183860+05:1800 stdout `
This comes out to 45 bytes long, while `conmon` wants only under 44 bytes for a timestamp
